# Generated by Django 4.0.3 on 2022-05-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_post_category_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
